return {
    "petertriho/nvim-scrollbar",
    -- event = { "VeryLazy" },
    event = "BufReadPre",
    opts = {
        hide_if_all_visible = true,
        handle = {
            -- color = "#0d6980",
            -- color = "#2aa198",
            -- color = "#002b36",
            -- color = "#586e75",
            color = "#839496",
        },
        marks = {
            Search = { color = "#d33682" },
            Error = { color = "#dc322f" },
            Warn = { color = "#b58900" },
            Info = { color = "#2aa198" },
            Hint = { color = "#268bd2" },
            Misc = { color = "#6c71c4" },
        },

        excluded_filetypes = {
            "TelescopeResults",
            "blink-cmp-menu",
            "cmp_docs",
            "cmp_menu",
            -- "dropbar_menu",
            -- "dropbar_menu_fzf",
            -- "DressingInput",
            -- "terminal",
            -- "nofile",
            -- "noice",
            -- "prompt",
            -- "TelescopePrompt",
            -- "TelescopePrompt",
            -- "noice",
            -- "LspsagaHover",
            -- "neo-tree",
        },
    },
}
